site_name: Tech Knowledge Base
site_description: Base de coneixement de l'equip Tech

theme:
  name: material #mkdocs material readthedocs
  language: ca

  custom_dir: overrides
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.path # Breadcrumbs
    - navigation.top # Botó "tornar a dalt"
    #- navigation.tabs # Menú principal en pestanyes a la part superior
    #- navigation.sections # Agrupa seccions al lateral
    #- navigation.expand # Obre seccions automàticament

    - search.suggest # Suggeriments durant la cerca
    - search.highlight # Ressalta els termes cercats

    - content.code.copy # Botó per copiar blocs de codi
    - content.code.annotate

    - toc.follow # TOC segueix l'scroll

plugins:
    - search

markdown_extensions:
  - admonition # !!! note, !!! warning, !!! tip, etc.
  - pymdownx.emoji # :smile: :heart: :+1:
  - pymdownx.details # Permet blocs desplegables (??? info)
  - pymdownx.highlight: # Ressaltat avançat de sintaxi
      anchor_linenums: true
  - pymdownx.superfences: # Millora els blocs de codi i Mermaid
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
  - pymdownx.snippets # Reutilització de contingut entre fitxers
  - pymdownx.tabbed # Permet pestanyes dins del contingut (=== "PowerShell", === "Bash")
  - tables # Taules Markdown
  - attr_list # Permet afegir atributs HTML/CSS als elements
  - md_in_html # Permet Markdown dins de blocs HTML
  - pymdownx.keys # Mostrar tecles (Ctrl+C, Alt+F4...)
  - pymdownx.tasklist: # Checklists interactives
      custom_checkbox: true

extra_javascript:
    - https://unpkg.com/mermaid@10/dist/mermaid.min.js
    - assets/javascripts/mermaid-init.js
    - assets/javascripts/status-warning.js # Avisos segons l'estat i la data de revisió

nav:
  - Guia de la KB: index.md

  - 01 - Operacions:
      - Postgres:
          - Configuració postgres_fdw: 01/postgres/configurar-postgres_fdw.md
          - Migració de dades amb postgres_fdw: 01/postgres/migrar-taules-develrw-de-pro-a-hall.md

  - 02 - Processos de negoci:
    - 0201: index.md

  - 03 - Dades i analítica:
    - Projecte: index.md

  - 04 - Servidors i Infraestructura:
      - edison:
          - GISCE gateway: 04/edison/gateway-gisce.md

  - 05 - Seguretat:
    - 0501: index.md

  - 06 - Projectes:
    - 0601: index.md

  - 07 - Desenvolupament:
    - 0701: index.md

  - 08 - Documentació:
    - 0801: index.md

  - 09 - Formació:
    - 0901: index.md

  - 10 - Telecomunicacions:
    - Plantes:
      - Cardedeu: telecom/cardedeu.md
    - Components:
      - SmartLogger: ot/smartlogger.md

  - 99 - Altres:
    - 9901: index.md

  - contribute:
    - Contribuir a la KB: contribute/contribute.md
